version: '3.8'

services:
  backend: 
    build: ./server
    container_name : backend_c_latest
    ports:  
     - "3000:3000"

  frontend:
    build: ./client
    container_name : frontend_c_latest
    ports: 
     - "5173:5173"
    stdin_open: true
    tty: true