name: Wonderwave CI/CD  # Descriptive and specific name

on:
  push:  # Trigger on push events
    branches:  # Only run for pushes to
      - main  # The 'main' branch (adjust if needed)

jobs:
  build-and-test:  # Combined name for clarity
    runs-on: ubuntu-latest  # Or the desired runner OS

    steps:
      - uses: actions/checkout@v3  # Checkout your code

      - name: Use Node.js 20  # Adjust if needed for project compatibility
        uses: actions/setup-node@v3
        with:
          node-version: "20.11.0"

      - name: Install dependencies (server) && Run tests
        run: cd server && ls # Install dependencies in the server directory



