name: Wonderwave CI/CD  # Descriptive and specific name

on:
  push:  # Trigger on push events
    branches:  # Only run for pushes to
      - main  # The 'main' branch (adjust if needed)

jobs:
  build-and-test:  # Combined name for clarity
    runs-on: ubuntu-latest  # Or the desired runner OS

    steps:
      - uses: actions/checkout@v3  # Checkout your code

      - name: Use Node.js 20  # Adjust if needed for project compatibility
        uses: actions/setup-node@v3
        with:
          node-version: "20.11.0"

      - name: Install dependencies (server)
        run: |
          cd server 
          npm ci 

      - name: Run tests
        run: |
          cd server 
          npx jest

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push Docker image (server)
        uses: docker/build-push-action@v2
        with:
          context: server
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/server_hub:latest

      - name: Build and push Docker image (client)
        uses: docker/build-push-action@v2
        with:
          context: client
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/client_hub:latest